Javascript carousel - Vorleak Yek
vorleakyek/m2-0723-code-solutions pull request #7
Opened 2023-07-24 23:30 UTC by vorleakyek

https://github.com/vorleakyek/m2-0723-code-solutions/assets/76607726/42508c8e-0473-4976-9a57-b9426635baa6

2023-07-25 01:52 UTC, TimelikeClosure requested changes

2023-07-25 01:52 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +autoPlay(getUpdatedValue);
It seems like, the way `getUpdatedValue` is being used, it doesn't add any functionality.

2023-07-25 01:52 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +}
`autoPlay` would be more self-contained if it handled clearing the previous interval internally.

2023-07-25 01:52 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +}
I'd suggest tying `event.target`s and DOM queries to something more unique than `tagName`s. For example, by using classes.

2023-07-26 06:08 UTC, vorleakyek commented
Okay, I made some changes based on the comments above. Please let make know if there is something that I should revise again.

2023-08-08 03:12 UTC, TimelikeClosure approved these changes

2023-08-26 03:48 UTC, merged